# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosegcotizador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('clave_horario', models.IntegerField()),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('clave_horario', models.IntegerField()),
                ('cp_sucursal', models.TextField()),
                ('calle_sucursal', models.TextField()),
                ('estado_sucursal', models.TextField()),
                ('colonia_sucursal', models.TextField()),
            ],
        ),
    ]
