# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosegcotizador', '0002_horario_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerechoMembresia',
            fields=[
                ('id_derechoMembresia', models.AutoField(primary_key=True, serialize=False)),
                ('precio_derecho_membresia', models.IntegerField()),
                ('vigencia', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
